--TESTING PROCEDURES


SELECT * FROM USERS;
SELECT * FROM CART;
SELECT * FROM PRICES;
SELECT * FROM PRODUCT;
SELECT * FROM CART_ITEMS;
SELECT * FROM STORE;
SELECT * FROM STORE_MANAGER;



EXECUTE UPDATE_OR_INSERT_USER('Ethan Davis', '543 Cedar Lane', '234-567-8901');

EXECUTE UPDATE_OR_INSERT_USER('Grace Johnson', '876 Birch Road', '567-890-1234');

EXECUTE UPDATE_OR_INSERT_USER('Ryan Taylor', '109 Oak Street', '890-123-4567');



EXECUTE ADD_TO_CART_ITEMS('Jane Smith','Whole milk',2,'Debit', 'Y');

EXECUTE ADD_TO_CART_ITEMS('MikeJohnson ','HP Laptop',1,'Debit', 'N');

EXECUTE ADD_TO_CART_ITEMS('Alex Clark','Spaghetti',3,'Debit', 'N');