/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ServiceCenterManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.QualityAssuranceCenter;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;


public class ServiceCenterManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ServiceCenterManagerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private QualityAssuranceCenter organization;
    private Enterprise enterprise;
    private Network network;
    public ServiceCenterManagerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, QualityAssuranceCenter organization, Enterprise enterprise, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.network=network;
        btnManageTechnician.setVisible(false);
        btnUserAccount.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageTechnician = new javax.swing.JButton();
        btnUserAccount = new javax.swing.JButton();
        btnWorkQueue = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("My Work Area - ServiceCenter Manager Role");

        btnManageTechnician.setBackground(new java.awt.Color(204, 255, 204));
        btnManageTechnician.setForeground(new java.awt.Color(51, 0, 51));
        btnManageTechnician.setText("Manage Technician");
        btnManageTechnician.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageTechnicianActionPerformed(evt);
            }
        });

        btnUserAccount.setBackground(new java.awt.Color(204, 255, 204));
        btnUserAccount.setForeground(new java.awt.Color(51, 0, 51));
        btnUserAccount.setText("Manage User Account");
        btnUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserAccountActionPerformed(evt);
            }
        });

        btnWorkQueue.setBackground(new java.awt.Color(204, 255, 204));
        btnWorkQueue.setForeground(new java.awt.Color(51, 0, 51));
        btnWorkQueue.setText("Manage Work Queue");
        btnWorkQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkQueueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnManageTechnician)
                            .addComponent(btnUserAccount)
                            .addComponent(btnWorkQueue)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(214, 214, 214))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnManageTechnician, btnUserAccount, btnWorkQueue});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnManageTechnician)
                .addGap(18, 18, 18)
                .addComponent(btnUserAccount)
                .addGap(18, 18, 18)
                .addComponent(btnWorkQueue)
                .addContainerGap(337, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageTechnicianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageTechnicianActionPerformed
        // TODO add your handling code here:
        ManageTechnicianJPanel mlajp = new ManageTechnicianJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("ManageTechnicianJPanel", mlajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageTechnicianActionPerformed

    private void btnUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserAccountActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnUserAccountActionPerformed

    private void btnWorkQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkQueueActionPerformed

        // TODO add your handling code here:
        ManageWorkQueueJPanel mwqtjp = new ManageWorkQueueJPanel(userProcessContainer, account, organization, enterprise, network);
        userProcessContainer.add("ManageWorkQueueJPanel", mwqtjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnWorkQueueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageTechnician;
    private javax.swing.JButton btnUserAccount;
    private javax.swing.JButton btnWorkQueue;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
